### ISSUE TITLE
[BUG] Cheap Advanced Machine Blocks by Breaking IC2 Metal Bender

### ISSUE THREAD

**Issue by Mr-Rixa** [AllTheMods/ATM3-Expert#170] opened 2019-12-07 20:30 UTC
## Expected Behavior

Metal Bender breaks into a **Machine Block**

## Current Behavior

Metal Bender breaks into a **Advanced Machine Block**

## Steps to Reproduce

1. Place down a IC2 Metal Bender
2. Break it with a pickaxe
3. Pick up advanced machine block
4. ???
5. Profit

**Comment by phantamanta44** [comment] 2019-12-19 18:12
isn't this intended behaviour in ic2? you usually need a wrench to dismantle machines

**Comment by Mr-Rixa** [comment] 2019-12-19 18:34
Yes it indeed is intended mechanics of ic2, BUT making Metal Bender in this pack doesn't require any advanced machine blocks, it's a "tier 1" machine. In this pack you need steel to make advanced machine blocks and you get to steel on "tier 3".

**Comment by TheGoldCrayon** [comment] 2020-01-03 20:17
fixed in 1.4.0

**Closed as completed by TheGoldCrayon** 2020-01-03 20:17 UTC
